Remove-Item -Recurse -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\screens"
Remove-Item -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\services\ai_service.dart"
Remove-Item -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\services\ai_service_mobile.dart"
Remove-Item -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\services\ai_service_stub.dart"
Remove-Item -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\services\email_sender_mobile.dart"
Remove-Item -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\services\email_sender_stub.dart"
Remove-Item -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\services\otp_service.dart"
Remove-Item -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\services\report_service.dart"
Remove-Item -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\services\auth_service.dart"
Remove-Item -Recurse -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\models"
Remove-Item -Force "f:\Smart_Neighborhood_Reporting_App_New\lib\mock_data.dart"
