// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmoLKgj_MMZ0PgLImb3MPeh-Lm9k8IpII',
    appId: '1:332428796210:web:1b1e9e868eb53e129eb72b',
    messagingSenderId: '332428796210',
    projectId: 'smart-neighborhood-6e4af',
    authDomain: 'smart-neighborhood-6e4af.firebaseapp.com',
    storageBucket: 'smart-neighborhood-6e4af.firebasestorage.app',
    measurementId: 'G-00ZSMXSVXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVi-Zrs2bmsWeM7Mj1HTyr2zDe4M3P3jY',
    appId: '1:332428796210:android:b79c74695ca856e19eb72b',
    messagingSenderId: '332428796210',
    projectId: 'smart-neighborhood-6e4af',
    storageBucket: 'smart-neighborhood-6e4af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsb7Jf3st289-ARxFWI3-lyQEsJNORjAU',
    appId: '1:332428796210:ios:75c906a2b8739edd9eb72b',
    messagingSenderId: '332428796210',
    projectId: 'smart-neighborhood-6e4af',
    storageBucket: 'smart-neighborhood-6e4af.firebasestorage.app',
    iosBundleId: 'com.example.smartNeighborhoodReportingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmoLKgj_MMZ0PgLImb3MPeh-Lm9k8IpII',
    appId: '1:332428796210:web:75890368d337c5df9eb72b',
    messagingSenderId: '332428796210',
    projectId: 'smart-neighborhood-6e4af',
    authDomain: 'smart-neighborhood-6e4af.firebaseapp.com',
    storageBucket: 'smart-neighborhood-6e4af.firebasestorage.app',
    measurementId: 'G-HFJ85GX6Q0',
  );
}
